Numpy i Macierze

In [1]:
import numpy as np

In [2]:
arr_x = np.array([[1, 2], 
                  [3, 4]])
arr_y = np.array([[3, 4], 
                 [5, 6]])

In [3]:
arr_x = arr_x.T

In [4]:
arr_x ** arr_y

array([[   1,   81],
       [  32, 4096]])

In [5]:
arr_y = np.sqrt(arr_y)
arr_y

array([[1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [6]:
arr_x > arr_y

array([[False,  True],
       [False,  True]])

In [7]:
arr_a = np.ones((5, 5))
arr_a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
arr_b = np.arange(10, 100, 10)
arr_b
arr_c = np.ones((10, 10))
arr_c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
for i in range(1, 10):
    for j in range(1, 10):
        arr_c[i][j] = arr_c[i][j] * (i * j) 

In [10]:
arr_c

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 1.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 1.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 1.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 1.,  6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 1.,  7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 1.,  8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 1.,  9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [11]:
arr_c.T

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 1.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 1.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 1.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 1.,  6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 1.,  7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 1.,  8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 1.,  9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [12]:
def my_trig_sum(a, b):
    """ 
    summing trgonometry values
    """
    out_1 = np.sin(a) + np.cos(b)
    out_2 = np.sin(b) + np.cos(a)

    return out_1, out_2, [out_1, out_2]

In [13]:
c, d, e = my_trig_sum(2, 3)
print(f"c = {c}, d = {d}, e = {e}")

c = -0.0806950697747637, d = -0.2750268284872752, e = [-0.0806950697747637, -0.2750268284872752]


In [14]:
def print_greeting(day='Monday', name='Jan'):
    print(f"Good {day}, {name}")

print_greeting()

Good Monday, Jan
